# Generated by Django 2.2.6 on 2019-11-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20191103_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='tel',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default='13613726612', max_length=32),
        ),
    ]
